### ISSUE TITLE
Replace tick and cross symbols (Nov 2019)

### ISSUE THREAD

**Issue by daraghbroderick** [raspberrypilearning/jazzy-jumpers#14]
Replace tick and cross symbols throughout and in starter project to make project more translation friendly.

**Comment by libxx1** [comment]
@ninaszymor can you lend your translation knowledge to this issue and let me know if it's something that still needs resolving please? Cheers, Liz

**Comment by ninaszymor** [comment]
@libxx1 the issue with cross and tick is that these symbols do not mean the same thing in all cultures and languages so we should replace them with something less culture-specific, for example a sad face emoji for 'wrong' and happy face emoji for 'correct'. Or even better, the symbols could be replaced with the words 'correct' and 'wrong'. Hope that makes sense.

**Comment by libxx1** [comment]
Ah thanks @ninaszymor , that makes perfect sense. @MarcScott @rik-cross assigning to you so you can discuss what approach we should take here to make our projects translate easier across cultures.

**Comment by libxx1** [comment]
Hey @majamanojlovic , 

If we change the costumes 'right' and 'wrong' on the 'Button4' sprite to these..... https://scratch.mit.edu/projects/181128260 

Does that work for translation better than the tick and cross costumes shown on this page?
https://learning-admin.raspberrypi.org/en/projects/jazzy-jumpers/6

If so I'll update page 6 to show the new costumes.

**Comment by majamanojlovic** [comment]
@libxx1 yes, that would definitely be more translation friendly.
